/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Versioned Health */
        get: operations["getVersionedHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Desktop Configuration */
        get: operations["getVersionedConfig"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice-assets/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cache Voice Presentation Assets */
        post: operations["cacheVoiceAssets"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/voice-assets/{voice_key}/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voice_key: string;
                kind: "avatar" | "sample";
            };
            cookie?: never;
        };
        /** Read Cached Voice Presentation Asset */
        get: operations["getVoiceAsset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workflow History */
        get: operations["listWorkflows"];
        put?: never;
        /** Create Workflow */
        post: operations["createWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        /** Get Workflow */
        get: operations["getWorkflow"];
        put?: never;
        post?: never;
        /** Delete Unfinished Workflow */
        delete: operations["deleteWorkflow"];
        options?: never;
        head?: never;
        /** Patch Draft Workflow */
        patch: operations["patchDraftWorkflow"];
        trace?: never;
    };
    "/workflows/active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Active Workflow Restart Candidates */
        get: operations["listActiveWorkflows"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        /** Get Workflow Workspace Projection */
        get: operations["getWorkflowWorkspace"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Workflow Workspace Revision */
        patch: operations["patchWorkflowWorkspace"];
        trace?: never;
    };
    "/workflows/{workflow_id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        /** List Workflow Items */
        get: operations["listWorkflowItems"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/items/{item_id}/content/{content_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
                item_id: string;
                content_id: string;
            };
            cookie?: never;
        };
        /** Read Bounded Workflow Item Content */
        get: operations["getWorkflowItemContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        /** List Workflow Artifacts */
        get: operations["listWorkflowArtifacts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Terminal Workflow */
        post: operations["archiveWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/source-imports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Source Import */
        post: operations["createSourceImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-imports/{import_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        /** Get Source Import */
        get: operations["getSourceImport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-imports/{import_id}/generations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Source Import Generation */
        post: operations["createSourceImportGeneration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-imports/{import_id}/generations/{generation}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: components["parameters"]["ImportId"];
                generation: number;
            };
            cookie?: never;
        };
        /** Get Source Import Generation */
        get: operations["getSourceImportGeneration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-imports/{import_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Write Source Import Content */
        put: operations["writeSourceImportContent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-imports/{import_id}/generations/{generation}/writer-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Source Writer Ticket */
        post: operations["createSourceWriterTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/source-imports/{import_id}/abort": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abort Source Import */
        post: operations["abortSourceImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Parse Workflow */
        post: operations["parseWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Workflow */
        post: operations["generateWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/export-zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create or Reuse ZIP Delivery Artifact */
        post: operations["exportWorkflowZip"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/retry-hold": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Hold Automatic Retry */
        post: operations["holdWorkflowRetry"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause Workflow */
        post: operations["pauseWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Workflow */
        post: operations["resumeWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Workflow Target */
        post: operations["retryWorkflowTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/reconcile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reconcile Workflow Target */
        post: operations["reconcileWorkflowTarget"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Workflow */
        post: operations["cancelWorkflow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/reruns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Workflow Rerun */
        post: operations["createWorkflowRerun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/external-records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ensure External Record Mapping */
        post: operations["ensureExternalRecord"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-records/{mapping_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get External Record Mapping */
        get: operations["getExternalRecord"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-records/{mapping_id}/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire External Record Lease */
        post: operations["acquireExternalRecordLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/external-operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare External Operation */
        post: operations["prepareExternalOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-operations/{operation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get External Operation */
        get: operations["getExternalOperation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-operations/{operation_id}/begin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin External Operation */
        post: operations["beginExternalOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-operations/{operation_id}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record External Submission */
        post: operations["observeExternalSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/external-operations/{operation_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve External Operation */
        post: operations["resolveExternalOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/attempts/{attempt_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve Attempt */
        post: operations["resolveAttempt"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/event-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Workflow Event Ticket */
        post: operations["createWorkflowEventTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workflows/{workflow_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Workflow Events */
        get: operations["streamWorkflowEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/content-tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Artifact Content Ticket */
        post: operations["createArtifactContentTicket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artifacts/{artifact_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Artifact Content */
        get: operations["readArtifactContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        JsonObject: {
            [key: string]: unknown;
        };
        WorkflowCreateRequest: {
            workflow_type: string;
            business_key?: string;
            configuration: components["schemas"]["JsonObject"];
        };
        WorkflowPatchRequest: {
            expected_state_version: number;
            configuration_revision?: number | null;
            configuration?: components["schemas"]["JsonObject"];
            item_overrides?: {
                item_id: string;
                patch: components["schemas"]["JsonObject"];
            }[];
        };
        ParseRequest: {
            expected_state_version: number;
            source_artifact_id?: string;
        };
        GenerateRequest: {
            expected_state_version: number;
            configuration_revision?: number | null;
            reason?: string | null;
            /** @enum {string|null} */
            generation_mode?: "composite_cut" | "single_segment" | null;
            provider?: string | null;
            account_scope?: string | null;
            item_ids?: string[] | null;
        };
        ExportZipRequest: {
            expected_state_version: number;
            include_item_ids?: string[] | null;
        };
        VoiceAssetCacheRequest: {
            voice_keys: string[];
        };
        VoiceAssetCacheResponse: {
            /** @constant */
            status: "ok";
            cached: {
                [key: string]: {
                    [key: string]: boolean;
                };
            };
        };
        GenerationRequest: {
            expected_state_version: number;
        };
        WorkflowCommandRequest: {
            expected_state_version: number;
            reason?: string;
        };
        CommandTarget: {
            /** @constant */
            target_type: "STEP";
            step_id: string;
        } | {
            /** @constant */
            target_type: "ITEM";
            step_id: string;
            item_id: string;
        } | {
            /** @constant */
            target_type: "WORK_UNIT";
            work_unit_id: string;
        } | {
            /** @constant */
            target_type: "WORK_UNIT_ATTEMPT";
            work_unit_attempt_id: string;
        } | {
            /** @constant */
            target_type: "PROVIDER_RECEIPT";
            provider_receipt_id: string;
        } | {
            /** @constant */
            target_type: "EXTERNAL_OPERATION";
            external_operation_id: string;
        };
        /** @description Resolve is evidence-driven and cannot target an aggregate STEP or ITEM projection. */
        ResolutionTarget: {
            /** @constant */
            target_type: "WORK_UNIT";
            work_unit_id: string;
        } | {
            /** @constant */
            target_type: "WORK_UNIT_ATTEMPT";
            work_unit_attempt_id: string;
        } | {
            /** @constant */
            target_type: "PROVIDER_RECEIPT";
            provider_receipt_id: string;
        } | {
            /** @constant */
            target_type: "EXTERNAL_OPERATION";
            external_operation_id: string;
        };
        TargetedCommandRequest: {
            expected_state_version: number;
            expected_target_state_version: number;
            expected_attempt_id?: string;
            reason?: string;
            target: components["schemas"]["CommandTarget"];
        };
        ControlCommandRequest: components["schemas"]["WorkflowCommandRequest"];
        ResolveRequest: {
            expected_state_version: number;
            expected_target_state_version: number;
            target: components["schemas"]["ResolutionTarget"];
            /** @enum {string} */
            decision: "CONFIRMED" | "NOT_SUBMITTED" | "BLOCKED";
            evidence: {
                source: string;
                evidence_hash: string;
                reference?: string;
                summary?: string;
            };
        };
        RerunRequest: {
            expected_group_state_version: number;
            source_workflow_id?: string;
            reason?: string;
        };
        ExternalRecordRequest: {
            external_system: string;
            account_scope: string;
            business_record_key: string;
            mapping_version: string;
            item_id?: string | null;
        };
        ExternalRecord: {
            external_record_mapping_id: string;
            external_system: string;
            external_account_scope: string;
            business_record_key: string;
            external_record_id?: string | null;
            current_workflow_group_id?: string | null;
            local_workflow_id?: string | null;
            local_item_id?: string | null;
            current_operation_key?: string | null;
            mapping_version: string;
            /** @enum {string} */
            external_status: "UNKNOWN" | "PENDING" | "EXISTS" | "CREATED" | "UPDATED" | "VERIFIED" | "NOT_FOUND" | "AMBIGUOUS" | "BLOCKED";
            /** Format: date-time */
            last_verified_at?: string | null;
            last_error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        } & {
            [key: string]: unknown;
        };
        ExternalLeaseRequest: {
            owner_id: string;
            /** @default 60 */
            ttl_seconds: number;
        };
        ExternalLease: {
            lease_id: string;
            mapping_id: string;
            owner_id: string;
            fencing_token: number;
            /** Format: date-time */
            lease_until: string;
        };
        ExternalOperationRequest: {
            mapping_id: string;
            operation_key: string;
            payload: components["schemas"]["JsonObject"];
            mapping_version: string;
            item_id?: string | null;
        };
        ExternalLeaseReference: {
            lease_id: string;
            mapping_id: string;
            owner_id: string;
            fencing_token: number;
        };
        ExternalSubmissionRequest: {
            lease: components["schemas"]["ExternalLeaseReference"];
            external_record_id: string;
            canonical_key: string;
            summary?: components["schemas"]["JsonObject"];
        };
        ExternalOperation: {
            external_operation_id: string;
            external_record_mapping_id: string;
            workflow_id: string;
            item_id?: string | null;
            external_operation_key: string;
            target_payload_hash: string;
            mapping_version: string;
            state_version: number;
            /** @enum {string} */
            side_effect_state: "NOT_STARTED" | "INTENT_RECORDED" | "IN_FLIGHT" | "SUBMITTED" | "CONFIRMED" | "AMBIGUOUS" | "REJECTED";
            receipt: components["schemas"]["JsonObject"];
        } & {
            [key: string]: unknown;
        };
        ExternalResolveRequest: {
            /** @enum {string} */
            decision: "CONFIRMED" | "NOT_SUBMITTED" | "BLOCKED";
            /** @default desktop */
            resolved_by: string;
            evidence: {
                source: string;
                evidence_hash: string;
                reference?: string | null;
                summary?: string | null;
            };
        };
        /** @enum {string} */
        RetryScope: "NONE" | "WORKFLOW" | "ITEMS";
        WorkspaceAction: {
            /** @enum {string} */
            kind: "SERVICE" | "UI";
            /** @enum {string} */
            type: "PARSE" | "SAVE_CONFIGURATION" | "GENERATE" | "PAUSE" | "RESUME" | "CANCEL" | "RETRY" | "RECONCILE" | "RESOLVE" | "ARCHIVE" | "ABANDON" | "RERUN" | "EXPORT_ZIP" | "OPEN_VIEW" | "DOWNLOAD_ARTIFACT" | "DOWNLOAD_ZIP" | "RECONNECT";
            enabled: boolean;
            reason: string | null;
            target: components["schemas"]["JsonObject"] | null;
            expected_state_version: number | null;
            expected_target_state_version: number | null;
            expected_group_state_version: number | null;
            safe_to_retry: boolean;
            retry_scope: components["schemas"]["RetryScope"];
        };
        WorkspaceBlocker: {
            code: string;
            title: string;
            message: string;
            /** @enum {string} */
            severity: "INFO" | "WARNING" | "ERROR" | "BLOCKING";
            affected_item_ids: string[];
            retryable: boolean;
            safe_to_retry: boolean;
            retry_scope: components["schemas"]["RetryScope"];
            requires_reconcile: boolean;
            recovery_action: components["schemas"]["WorkspaceAction"] | null;
        };
        WorkspaceItem: {
            item_id: string;
            item_identity_key: string;
            sequence: number;
            item_type: string;
            normalized_content: string | null;
            content_ref: {
                content_id: string;
                size_bytes: number;
                content_hash: string;
                max_response_bytes: number;
            } | null;
            source_locator: string | null;
            metadata: {
                [key: string]: unknown;
            };
            skip_reason: string | null;
            content_hash: string;
            /** @enum {string} */
            status: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "AMBIGUOUS" | "CANCELLED" | "SKIPPED" | "UNRESOLVED";
            role: string | null;
            voice_key: string | null;
            attempt_count: number;
            error_code: string | null;
            user_message: string | null;
            retry_scope: components["schemas"]["RetryScope"];
            requires_reconcile: boolean;
            artifact_ids: string[];
            /** Format: date-time */
            updated_at: string;
        };
        ItemContentResponse: {
            workflow_id: string;
            item_id: string;
            content_id: string;
            state_version: number;
            item_state_version: number;
            content_hash: string;
            size_bytes: number;
            offset_bytes: number;
            next_offset_bytes: number;
            truncated: boolean;
            content: string;
        };
        WorkspaceArtifact: {
            artifact_id: string;
            workflow_id: string;
            item_id: string | null;
            step_id: string | null;
            work_unit_id: string | null;
            artifact_type: string;
            /** @enum {string} */
            lifecycle_state: "TEMP" | "READY" | "INVALID" | "DELETED";
            format: string | null;
            extension: string | null;
            mime_type: string | null;
            size_bytes: number | null;
            sha256: string | null;
            verified: boolean;
            filename: string | null;
            duration_ms: number | null;
            producer: string;
            producer_version: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        EffectiveConfiguration: {
            provider: string;
            /** @enum {string} */
            generation_mode: "composite_cut" | "single_segment";
            format: string;
            quality: string | null;
            preview: boolean;
            preview_limit: number | null;
            rate: number | null;
            pitch: number | null;
            volume: number | null;
            default_female_voice: string | null;
            default_male_voice: string | null;
            role_voices: {
                [key: string]: string | null;
            };
            role_configs: {
                [key: string]: {
                    rate: number | null;
                    pitch: number | null;
                    volume: number | null;
                };
            };
        };
        ConfigurationProjection: {
            configuration_revision: number;
            configuration_hash: string;
            effective: components["schemas"]["EffectiveConfiguration"];
            source_priority: {
                [key: string]: "GLOBAL" | "ROLE" | "ITEM";
            };
            frozen_fields: string[];
        };
        WorkspaceProgress: {
            total: number;
            completed: number;
            failed: number;
            cancelled: number;
            skipped: number;
            pending: number;
            deliverable: number;
            percent: number;
            deliverable_percent: number;
        };
        WorkspaceDelivery: {
            zip_artifact_id: string | null;
            zip_available: boolean;
            included_item_ids: string[];
            excluded_item_ids: string[];
            exclusion_reasons: {
                [key: string]: string;
            };
        };
        WorkspaceSync: {
            state_version: number;
            last_event_id: string | null;
            requires_resync: boolean;
        };
        WorkflowWorkspace: {
            schema_version: number;
            source_filename: string;
            snapshot: components["schemas"]["WorkflowSnapshot"];
            progress: components["schemas"]["WorkspaceProgress"];
            blockers: components["schemas"]["WorkspaceBlocker"][];
            available_actions: components["schemas"]["WorkspaceAction"][];
            current_target: {
                item_id: string;
                label: string;
                /** Format: date-time */
                started_at: string;
            } | null;
            items: components["schemas"]["WorkspaceItem"][];
            artifacts: components["schemas"]["WorkspaceArtifact"][];
            configuration: components["schemas"]["ConfigurationProjection"];
            provider: components["schemas"]["WorkspaceProvider"];
            delivery: components["schemas"]["WorkspaceDelivery"];
            sync: components["schemas"]["WorkspaceSync"];
        };
        WorkspaceProvider: {
            provider: string;
            /** @enum {string} */
            status: "UNKNOWN" | "READY" | "LOGIN_REQUIRED" | "EXPIRED" | "UNAVAILABLE" | "DISABLED";
            ready: boolean;
            reason: string;
            can_generate: boolean;
            /** @description Whether a foreground generate command may open/login the provider. */
            can_start_generation: boolean;
        };
        WorkflowWorkspaceEnvelope: {
            request_id: string;
            workspace: components["schemas"]["WorkflowWorkspace"];
        };
        ActiveWorkflowCandidate: {
            workflow: components["schemas"]["WorkflowSnapshot"];
            can_resume: boolean;
            can_takeover: boolean;
            resume_reason: string;
            requires_reconcile: boolean;
        };
        ActiveWorkflowListResponse: {
            workflows: components["schemas"]["ActiveWorkflowCandidate"][];
            limit: number;
            truncated: boolean;
        };
        WorkflowHistoryRecord: {
            id: string;
            workflow_id: string;
            source_filename: string;
            available_files: number;
            completed: number;
            failed: number;
            cancelled: number;
            skipped: number;
            total: number;
            pending: number;
            format: string;
            generation_mode: string;
            preview: boolean;
            zip_available: boolean;
            zip_artifact_id: string | null;
            failed_items: components["schemas"]["JsonObject"][];
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "ABANDONED" | "CLOSED";
            /** @enum {string} */
            result_status: "IN_PROGRESS" | "SUCCEEDED" | "PARTIAL_SUCCESS" | "FAILED" | "CANCELLED";
            /** @enum {string} */
            execution_state: "CREATED" | "PREPARING" | "RUNNING" | "WAITING_RETRY" | "WAITING_USER" | "RECOVERING" | "BLOCKED" | "TERMINAL";
            /** @enum {string} */
            control_state: "RUNNING" | "PAUSE_REQUESTED" | "PAUSED" | "TERMINATING" | "TERMINATED";
            state_version: number;
            can_delete: boolean;
            delete_reason: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            completed_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        WorkflowListResponse: {
            workflows: components["schemas"]["WorkflowHistoryRecord"][];
        };
        WorkItemInfo: {
            item_id: string;
            workflow_id: string;
            item_identity_key: string;
            item_type: string;
            sequence: number;
            normalized_content: string;
            content_hash: string;
            /** @enum {string} */
            status: "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "AMBIGUOUS" | "CANCELLED" | "SKIPPED" | "UNRESOLVED";
        } & {
            [key: string]: unknown;
        };
        WorkflowItemsResponse: {
            items: components["schemas"]["WorkItemInfo"][];
        };
        ArtifactInfo: {
            artifact_id: string;
            workflow_id: string;
            item_id?: string | null;
            step_id?: string | null;
            work_unit_id?: string | null;
            artifact_type: string;
            /** @enum {string} */
            lifecycle_state: "TEMP" | "READY" | "INVALID" | "DELETED";
            sha256: string | null;
            size_bytes: number | null;
            format: string | null;
            producer: string;
            producer_version: string | null;
            verified: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ArtifactListResponse: {
            artifacts: components["schemas"]["ArtifactInfo"][];
        };
        ExportZipArtifact: {
            artifact_id: string;
            workflow_id: string;
            /** @constant */
            artifact_type: "export-zip";
            /** @constant */
            lifecycle_state: "READY";
            sha256: string;
            size_bytes: number;
            /** @constant */
            format: "zip";
            producer: string;
            producer_version: string;
            /** @constant */
            verified: true;
            included_count: number;
            included_item_ids: string[];
            excluded_item_ids: string[];
            exclusion_reasons: {
                [key: string]: string;
            };
            filename: string;
            /** @constant */
            extension: ".zip";
            /** @constant */
            mime_type: "application/zip";
            duration_ms: number | null;
        };
        ExportZipResponse: {
            request_id: string;
            workflow_id: string;
            state_version: number;
            artifact: components["schemas"]["ExportZipArtifact"];
        };
        WorkflowSnapshot: {
            workflow_id: string;
            workflow_group_id: string;
            group_state_version: number;
            parent_workflow_id: string | null;
            /** @enum {string} */
            result_status: "IN_PROGRESS" | "SUCCEEDED" | "PARTIAL_SUCCESS" | "FAILED" | "CANCELLED";
            /** @enum {string} */
            execution_state: "CREATED" | "PREPARING" | "RUNNING" | "WAITING_RETRY" | "WAITING_USER" | "RECOVERING" | "BLOCKED" | "TERMINAL";
            /** @enum {string} */
            control_state: "RUNNING" | "PAUSE_REQUESTED" | "PAUSED" | "TERMINATING" | "TERMINATED";
            /** @enum {string} */
            cleanup_state: "NONE" | "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "DEFERRED";
            /** @enum {string} */
            status: "DRAFT" | "ACTIVE" | "ABANDONED" | "CLOSED";
            state_version: number;
            draft_revision: number;
            current_step_id: string | null;
            source_artifact_id: string | null;
            item_count: number;
            artifact_count: number;
            latest_event_id: string | null;
            latest_seq: number;
            last_error_code: string | null;
            last_error_message: string | null;
            latest_event?: components["schemas"]["WorkflowEvent"] | null;
            /** Format: date-time */
            updated_at: string;
        };
        WorkflowEnvelope: {
            request_id: string;
            workflow: components["schemas"]["WorkflowSnapshot"];
        };
        WorkflowDeleteResponse: {
            request_id: string;
            workflow_id: string;
            /** @constant */
            accepted_action: "delete";
            /** @constant */
            deleted: true;
        };
        CommandResponse: {
            request_id: string;
            workflow_id: string;
            accepted_action: string;
            /** @enum {string} */
            result_status: "IN_PROGRESS" | "SUCCEEDED" | "PARTIAL_SUCCESS" | "FAILED" | "CANCELLED";
            /** @enum {string} */
            execution_state: "CREATED" | "PREPARING" | "RUNNING" | "WAITING_RETRY" | "WAITING_USER" | "RECOVERING" | "BLOCKED" | "TERMINAL";
            /** @enum {string} */
            control_state: "RUNNING" | "PAUSE_REQUESTED" | "PAUSED" | "TERMINATING" | "TERMINATED";
            /** @enum {string} */
            cleanup_state: "NONE" | "PENDING" | "RUNNING" | "SUCCEEDED" | "FAILED" | "DEFERRED";
            state_version: number;
            current_snapshot: components["schemas"]["WorkflowSnapshot"];
            target_attempt_id: string | null;
            parse_results?: components["schemas"]["JsonObject"][];
            source_filename?: string;
            source_artifact_id?: string | null;
            parsed_artifact_id?: string | null;
        };
        SourceImportCreateRequest: {
            metadata: components["schemas"]["JsonObject"];
            expected_size_bytes?: number | null;
            expected_sha256?: string | null;
            content_type?: string | null;
        };
        SourceImportStatus: {
            source_import_id: string;
            workflow_id: string;
            staging_generation: number;
            /** @enum {string} */
            status: "CREATED" | "RECEIVING" | "READY" | "FAILED" | "EXPIRED" | "ABORTED";
            state_version: number;
            received_size_bytes: number;
            actual_size_bytes?: number | null;
            actual_sha256?: string | null;
            source_artifact_id: string | null;
            error_code?: string | null;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SourceImportGenerationStatus: {
            source_import_id: string;
            workflow_id: string;
            generation: number;
            /** @enum {string} */
            status: "CREATED" | "RECEIVING" | "READY" | "FAILED" | "EXPIRED" | "ABORTED";
            state_version: number;
            received_size_bytes: number;
            actual_size_bytes?: number | null;
            actual_sha256?: string | null;
            source_artifact_id: string | null;
            error_code?: string | null;
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        SourceImportCommandRequest: {
            expected_state_version: number;
            reason?: string;
        };
        EventTicketRequest: {
            last_event_id: string | null;
        };
        EventTicket: {
            readonly ticket: string;
            workflow_id: string;
            /** Format: date-time */
            expires_at: string;
        };
        ArtifactTicket: {
            readonly ticket: string;
            artifact_id: string;
            /** Format: date-time */
            expires_at: string;
            content_type: string | null;
            content_length: number | null;
            sha256: string | null;
            filename: string | null;
        };
        SourceWriterTicket: {
            grant: string;
            source_import_id: string;
            generation: number;
            /** Format: date-time */
            expires_at: string;
        };
        WorkflowEvent: {
            event_id: string;
            seq: number;
            workflow_id: string;
            mutation_id: string;
            schema_version: string;
            step_id?: string | null;
            item_id?: string | null;
            attempt_id?: string | null;
            correlation_id: string;
            causation_id: string | null;
            /** @enum {string} */
            actor_type: "USER" | "WORKER" | "RECOVERY" | "SCHEDULER" | "SYSTEM";
            actor_id?: string | null;
            event_type: string;
            phase?: string | null;
            payload: components["schemas"]["JsonObject"];
            /** Format: date-time */
            created_at: string;
        };
        ErrorResponse: {
            request_id: string;
            /** @enum {string} */
            error_code: "VALIDATION_ERROR" | "UNAUTHORIZED" | "FORBIDDEN" | "NOT_FOUND" | "IDEMPOTENCY_CONFLICT" | "IDEMPOTENCY_IN_PROGRESS" | "STATE_CONFLICT" | "CONFIGURATION_CONFLICT" | "CONFIG_FROZEN" | "CONTROL_STATE_CONFLICT" | "TARGET_REQUIRED" | "CONTENT_CONFLICT" | "ITEM_ALREADY_DELIVERED" | "PARSE_ERROR" | "AUTH_ERROR" | "TRANSIENT_PROVIDER_ERROR" | "PROVIDER_RATE_LIMITED" | "PROVIDER_LOGIN_REQUIRED" | "PROVIDER_QUOTA_EXCEEDED" | "PROVIDER_RECEIPT_SCOPE" | "SUBMISSION_AMBIGUOUS" | "RECONCILIATION_REQUIRED" | "EVIDENCE_REQUIRED" | "SEGMENT_BOUNDARIES_UNVERIFIED" | "DOWNLOAD_ERROR" | "ARTIFACT_INVALID" | "PERSISTENCE_ERROR" | "PERSISTENCE_AMBIGUOUS" | "CURSOR_EXPIRED" | "CURSOR_INVALID" | "API_VERSION_RETIRED" | "SCHEMA_MISMATCH" | "DEPENDENCY_NOT_READY" | "EXTERNAL_CAPABILITY_REQUIRED" | "EXTERNAL_RUNTIME_ERROR" | "EXTERNAL_RECONCILIATION_REQUIRED" | "EXTERNAL_MAPPING_VERSION_CONFLICT" | "EXTERNAL_SCOPE_CONFLICT" | "EXTERNAL_OPERATION_ACTIVE" | "EXTERNAL_STATE_CONFLICT" | "EXTERNAL_SUBMIT_UNKNOWN" | "EXTERNAL_NOT_FOUND_REQUIRES_MANUAL" | "USER_CANCELLED" | "WORKFLOW_CANCELLED" | "INTERNAL_ERROR" | "STALE_ATTEMPT" | "RESOURCE_EXHAUSTED" | "SOURCE_NOT_AVAILABLE" | "EXTERNAL_TARGET_AMBIGUOUS" | "EXTERNAL_VERIFY_MISMATCH" | "DRAFT_EXPIRED" | "ARTIFACT_ORPHANED" | "CLEANUP_ERROR" | "MIGRATION_ERROR" | "MIGRATION_REQUIRED" | "GENERATION_ALREADY_RUNNING" | "GENERATION_NOT_RUNNING" | "PROVIDER_UNAVAILABLE" | "UNSUPPORTED_MEDIA_TYPE" | "CONTENT_TOO_LARGE" | "ITEM_CONTENT_TOO_LARGE" | "INSUFFICIENT_STORAGE";
            message: string;
            retryable: boolean;
            side_effect_occurred: boolean;
            workflow_id?: string | null;
            step_id?: string | null;
            attempt_id?: string | null;
            details?: components["schemas"]["JsonObject"];
        };
    };
    responses: {
        /** @description Missing, invalid, expired or replayed capability/ticket. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource or sender is not authorized. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found or intentionally hidden. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description State, idempotency, target, content or cursor conflict. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Ticket or cursor is expired and must be recreated/re-synchronized. */
        Expired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Upload or decompressed content exceeds a configured limit. */
        PayloadTooLarge: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description File type or container is not allowed. */
        UnsupportedMediaType: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Request shape or value is invalid. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The bounded local queue is full or the provider requires backoff. */
        RateLimited: {
            headers: {
                /** @description Seconds before retrying the same operation. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The configured local storage budget is exhausted. */
        InsufficientStorage: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        WorkflowId: string;
        ImportId: string;
        AttemptId: string;
        ArtifactId: string;
        IdempotencyKey: string;
        LastEventId: string;
        SseTicket: string;
        ArtifactTicket: string;
        StagingGeneration: number;
        SourceWriteGrant: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersionedHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local backend readiness and contract version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonObject"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getVersionedConfig: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Non-secret renderer configuration and voice catalog. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JsonObject"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    cacheVoiceAssets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VoiceAssetCacheRequest"];
            };
        };
        responses: {
            /** @description Best-effort local cache result; failures fall back to catalog URLs. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VoiceAssetCacheResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getVoiceAsset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                voice_key: string;
                kind: "avatar" | "sample";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cached image or audio sample. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                    "image/png": string;
                    "audio/mpeg": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listWorkflows: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded history projection without storage paths. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    createWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCreateRequest"];
            };
        };
        responses: {
            /** @description Existing workflow for the same idempotency key and request hash. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            /** @description New draft workflow. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    getWorkflow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest persisted workflow snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deleteWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCommandRequest"];
            };
        };
        responses: {
            /** @description Unfinished workflow and its local data were physically deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDeleteResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    patchDraftWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowPatchRequest"];
            };
        };
        responses: {
            /** @description Updated draft snapshot. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    listActiveWorkflows: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded active workflows with safe takeover/resume facts. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActiveWorkflowListResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getWorkflowWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-owned snapshot, item, artifact, blocker and action projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowWorkspaceEnvelope"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    patchWorkflowWorkspace: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowPatchRequest"];
            };
        };
        responses: {
            /** @description Updated server-owned workspace projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowWorkspaceEnvelope"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    listWorkflowItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Normalized item projection for one workflow. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowItemsResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getWorkflowItemContent: {
        parameters: {
            query?: {
                expected_state_version?: number;
                offset_bytes?: number;
                max_response_bytes?: number;
            };
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
                item_id: string;
                content_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Bounded item text referenced by a workspace projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemContentResponse"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            /** @description Item content exceeds the bounded detail response limit. */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listWorkflowArtifacts: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Safe Artifact metadata; storage keys are omitted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactListResponse"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    archiveWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCommandRequest"];
            };
        };
        responses: {
            /** @description Workflow hidden from the history projection while its facts remain retained. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    createSourceImport: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceImportCreateRequest"];
            };
        };
        responses: {
            /** @description Existing import session for the same request hash. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            /** @description Created import session. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    getSourceImport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted import/generation status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createSourceImportGeneration: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description New staging generation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    getSourceImportGeneration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                import_id: components["parameters"]["ImportId"];
                generation: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Immutable status for the requested generation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportGenerationStatus"];
                };
            };
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    writeSourceImportContent: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
                "X-Staging-Generation": components["parameters"]["StagingGeneration"];
                "X-Source-Write-Grant": components["parameters"]["SourceWriteGrant"];
            };
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description Already READY with the same server-calculated fingerprint. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            /** @description Content verified and bound to a READY source Artifact. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            /** @description Same generation is still being written. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            409: components["responses"]["Conflict"];
            413: components["responses"]["PayloadTooLarge"];
            415: components["responses"]["UnsupportedMediaType"];
            429: components["responses"]["RateLimited"];
            507: components["responses"]["InsufficientStorage"];
        };
    };
    createSourceWriterTicket: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                import_id: components["parameters"]["ImportId"];
                generation: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerationRequest"];
            };
        };
        responses: {
            /** @description Opaque single-use source writer grant. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceWriterTicket"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    abortSourceImport: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                import_id: components["parameters"]["ImportId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SourceImportCommandRequest"];
            };
        };
        responses: {
            /** @description Current generation marked ABORTED. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceImportStatus"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    parseWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ParseRequest"];
            };
        };
        responses: {
            /** @description Existing parse command result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Parse accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    generateWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Existing command result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Current run accepted or resumed. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    exportWorkflowZip: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportZipRequest"];
            };
        };
        responses: {
            /** @description Existing export command result for the same idempotency key. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportZipResponse"];
                };
            };
            /** @description Deterministic ZIP Artifact created or reused for this terminal workflow. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportZipResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    holdWorkflowRetry: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowCommandRequest"];
            };
        };
        responses: {
            /** @description Existing hold command result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Automatic retry held for user configuration. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    pauseWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlCommandRequest"];
            };
        };
        responses: {
            /** @description Idempotent no-op or existing result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Pause accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    resumeWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlCommandRequest"];
            };
        };
        responses: {
            /** @description Idempotent no-op or existing result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Resume accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    retryWorkflowTarget: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetedCommandRequest"];
            };
        };
        responses: {
            /** @description Target retry accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    reconcileWorkflowTarget: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TargetedCommandRequest"];
            };
        };
        responses: {
            /** @description Read-only reconciliation accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    cancelWorkflow: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlCommandRequest"];
            };
        };
        responses: {
            /** @description Idempotent terminal no-op. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            /** @description Cancellation accepted; unresolved side effects remain BLOCKED. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    createWorkflowRerun: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RerunRequest"];
            };
        };
        responses: {
            /** @description New run created; parent run remains immutable. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            /** @description New run creation accepted for asynchronous preparation. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowEnvelope"];
                };
            };
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    ensureExternalRecord: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalRecordRequest"];
            };
        };
        responses: {
            /** @description Idempotently reused mapping. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalRecord"];
                };
            };
            /** @description Durable business-key mapping. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalRecord"];
                };
            };
            409: components["responses"]["Conflict"];
            503: components["responses"]["InsufficientStorage"];
        };
    };
    getExternalRecord: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mapping_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current mapping projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalRecord"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    acquireExternalRecordLease: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                mapping_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalLeaseRequest"];
            };
        };
        responses: {
            /** @description Fenced lease for one external mapping. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalLease"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    prepareExternalOperation: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalOperationRequest"];
            };
        };
        responses: {
            /** @description Idempotently reused operation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalOperation"];
                };
            };
            /** @description Operation intent recorded before any external call. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalOperation"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    getExternalOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current external operation projection. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalOperation"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    beginExternalOperation: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalLeaseReference"];
            };
        };
        responses: {
            /** @description Local IN_FLIGHT state committed; the worker may call the external system. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalOperation"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    observeExternalSubmission: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalSubmissionRequest"];
            };
        };
        responses: {
            /** @description External receipt observed and bound locally. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalOperation"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    resolveExternalOperation: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                operation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExternalResolveRequest"];
            };
        };
        responses: {
            /** @description Evidence-backed manual resolution. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExternalOperation"];
                };
            };
            409: components["responses"]["Conflict"];
        };
    };
    resolveAttempt: {
        parameters: {
            query?: never;
            header: {
                "X-Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                attempt_id: components["parameters"]["AttemptId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveRequest"];
            };
        };
        responses: {
            /** @description Evidence-backed manual decision accepted. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommandResponse"];
                };
            };
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["RateLimited"];
        };
    };
    createWorkflowEventTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventTicketRequest"];
            };
        };
        responses: {
            /** @description Short-lived, single-use SSE ticket. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventTicket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    streamWorkflowEvents: {
        parameters: {
            query?: never;
            header: {
                "Last-Event-ID"?: components["parameters"]["LastEventId"];
                "X-SSE-Ticket": components["parameters"]["SseTicket"];
            };
            path: {
                workflow_id: components["parameters"]["WorkflowId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persistent SSE snapshot/catch-up stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            410: components["responses"]["Expired"];
        };
    };
    createArtifactContentTicket: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Short-lived, single-use artifact read ticket. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArtifactTicket"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            429: components["responses"]["RateLimited"];
        };
    };
    readArtifactContent: {
        parameters: {
            query?: never;
            header: {
                "X-Artifact-Ticket": components["parameters"]["ArtifactTicket"];
            };
            path: {
                artifact_id: components["parameters"]["ArtifactId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Streamed content from an immutable Blob. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                    "audio/mpeg": string;
                    "audio/wav": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            410: components["responses"]["Expired"];
        };
    };
}
